builders:
  orm_m8:
    import: "package:f_orm_m8_sqlite/builder.dart"
    builder_factories: ["ormM8"]
    build_extensions: {".dart": [".adapter.m8.part"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]