targets:
  $default:
    builders:
      flutter_sqlite_m8_generator|flutter_orm_m8:
        enabled: true

builders:
  flutter_orm_m8:
    target: ":flutter_sqlite_m8_generator"
    import: "package:flutter_sqlite_m8_generator/builder.dart"
    builder_factories: ["ormM8"]
    build_extensions: {".dart": [".g.m8.part"]}
    auto_apply: root_package
    build_to: source
    applies_builders: ["source_gen|combining_builder"]