name: flutter_sqlite_m8_generator
description: Flutter package to generate SQLite fixture.
version: 0.0.1
author: Mircea-Tiberiu MATEI<matei_tm@yahoo.com>
homepage: https://github.com/matei-tm/flutter-sqlite-m8-generator

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  build: '>=0.12.0 <2.0.0'
  source_gen: ^0.9.0
  flutter_orm_m8: ^0.1.0

dev_dependencies:
  test: ^1.3.3

