name: flutter_sqlite_m8_generator
description: Flutter package to generate SQLite fixture in conjuction with the package flutter_orm_m8.
version: 0.0.4
author: Mircea-Tiberiu MATEI<matei_tm@yahoo.com>
homepage: https://github.com/matei-tm/flutter-sqlite-m8-generator

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  build: '>=0.12.0 <2.0.0'
  source_gen: ^0.9.0
  flutter_orm_m8: ^0.3.0

dev_dependencies:
  build_verify: ^1.1.0
  build_runner: ^1.0.0
  build_test: ^0.10.0
  source_gen_test: ^0.1.0
  test: ^1.3.3
